#!/bin/sh
exec 2>&1

# Directories and init
mkdir -p /etc/rsyslog
chown root.syslog /var/log
touch /var/log/syslog
chgrp -R "syslog" /var/log/syslog
touch /var/log/cron.log
chgrp -R "syslog" /var/log/cron.log
touch /var/log/daemon.log
chgrp -R "syslog" /var/log/daemon.log
chmod -R g+rw /var/log/
chgrp -R syslog /var/log
chmod -R g+rw /var/log/
if [ ! -d /var/run/rsyslog ]; then
    mkdir -p /var/run/rsyslog
    [ -z "syslog" ] || chown -R "syslog" /var/run/rsyslog
    [ -z "syslog" ] || chgrp -R "syslog" /var/run/rsyslog
fi
umask 077
# Run daeomon
exec /usr/sbin/rsyslogd -n -f /container/config/rsyslog.conf -iNONE
